language: node_js
os: linux
node_js:
- node
install:
- npm install -g mocha
- npm install chai
- npm install chai-http
- npm install express
- npm ci
script:
- npm test --passWithNoTests

notifications:
  email: false